#!/bin/sh
#set -x
#set -e

port=8888
while [ "$1" != "" ] 
do
        case $1 in
        -p)
                port=$2
                shift
                ;;
        *)
                echo "usage -p [number]"
                exit 1
                ;;
        esac
        shift
done

MYSCP="sshpass -p dev scp  -P $port  -o NoHostAuthenticationForLocalhost=yes"
MYSSH="sshpass -p dev ssh -p $port root@127.0.0.1 -o NoHostAuthenticationForLocalhost=yes"

ISOBZ=minix3_3_0_ide_copy.iso.bz2
rm -f $ISOBZ
$MYSCP -r device/* root@127.0.0.1:/
$MYSSH /root/create-iso.sh
$MYSCP root@127.0.0.1:/usr/src/releasetools/$ISOBZ .
if [ ! -e $ISOBZ ]
then
	echo "$ISOBZ Missing."
	exit 1
fi
echo "OK $ISOBZ was found"
echo
exit 0
