#!/bin/sh
set -e
set -x
rm -f install_test.img
rm -f minix-dev.iso
ISOBZ=minix3_2_1_ide_copy.iso.bz2
if [ ! -e $ISOBZ ] 
then
	echo "$ISOBZ is missing"
	exit
fi
cat $ISOBZ | bunzip2 > minix-dev.iso
../autoinstall/script/02_qemu_minix_base.install.expect -- --image install_test.img --cdrom minix-dev.iso 
