#!/bin/sh
set -x
set -e


MYSCP="sshpass -p dev scp  -P 8888  -o NoHostAuthenticationForLocalhost=yes"
MYSSH="sshpass -p dev ssh -p 8888 root@127.0.0.1 -o NoHostAuthenticationForLocalhost=yes"

mkdir -p test-reports
$MYSCP -r device/* root@127.0.0.1:/
if $MYSSH "cd /usr/src/test ; make"
if $MYSSH "cd /usr/src/test ; ./run.py"
then
	echo "some tests failed $?"
fi
$MYSCP root@127.0.0.1:/usr/src/test/test-reports/* test-reports/
