#!/bin/sh
set -x
set -e

port=8888
while [ "$1" != "" ] 
do
        case $1 in
        -p)
                port=$2
                shift
                ;;
        *)
                echo "usage -p [number]"
                exit 1
                ;;
        esac
        shift
done


MYSCP="sshpass -p dev scp  -P $port  -o NoHostAuthenticationForLocalhost=yes"
MYSSH="sshpass -p dev ssh -p $port root@127.0.0.1 -o NoHostAuthenticationForLocalhost=yes"

mkdir -p test-reports
$MYSCP -r device/* root@127.0.0.1:/
echo "Making tests"
if $MYSSH "cd /usr/src/test ; make"
then
	echo "Building the tests using make failed"
fi
echo "Running test for xml result"
if $MYSSH "cd /usr/src/test ; ./run.py"
then
	echo "some tests (using run.py) failed $?"
fi
#
# Run again for the console output
#
echo "Running tests using run"
if $MYSSH "cd /usr/src/test ; ./run"
then
	echo "some tests (using run) failed $?"
fi
$MYSCP root@127.0.0.1:/usr/src/test/test-reports/* test-reports/
